# Generated by Django 5.0.1 on 2024-07-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'managed': True},
        ),
    ]
