# Generated by Django 5.0.1 on 2024-07-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_staff_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'managed': False},
        ),
    ]
