services:
  web:
    build: .
    container_name: barcodescanner_django
    expose:
      - 8000
    volumes:
      - .:/app
      - static_volume:/app/static
    env_file:
      - mysite/.env
    depends_on:
      - barcodescanner-postgres
    develop:
      watch:
        - action: rebuild
          path: .
    ports:
      - 8000:8000
    environment:
      DJANGO_ENV: development

  barcodescanner-postgres:
    image: postgres:16
    container_name: barcodescanner_db
    env_file:
      - mysite/.env
    ports:
      - '5433:5433'
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
   pg_data:
   static_volume:


