services:
  web:
    build: .
    container_name: barcodescanner_django
    expose:
      - 8000
    volumes:
      - .:/app
      - static_volume:/app/static
    env_file:
      - mysite/.env
    depends_on:
      - barcodescanner-postgres
    restart: always
    image: reubenmonaghan/barcodescanner-web:latest

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
    ports:
      - 8000:8000
    depends_on:
      - web
    restart: always
    image: reubenmonaghan/barcodescanner-nginx:latest

  barcodescanner-postgres:
    image: postgres:16
    container_name: barcodescanner_db
    env_file:
      - mysite/.env
    ports:
      - '5433:5433'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
   pg_data:
   static_volume:

