# Generated by Django 5.0.1 on 2024-02-28 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qiasymphony24Load',
            fields=[
                ('Qiasymphony24Load_id', models.AutoField(primary_key=True, serialize=False)),
                ('Qiasymphony24Load_method', models.CharField(max_length=30)),
                ('Qiasymphony24Load_worksheet', models.CharField(max_length=12)),
                ('Qiasymphony24Check_result', models.BooleanField(default=False)),
                ('dateTime_check', models.DateTimeField(auto_now_add=True, verbose_name='date_and_time')),
                ('sampletube1', models.CharField(max_length=10)),
                ('sampletube2', models.CharField(max_length=10)),
                ('sampletube3', models.CharField(max_length=10)),
                ('sampletube4', models.CharField(max_length=10)),
                ('sampletube5', models.CharField(max_length=10)),
                ('sampletube6', models.CharField(max_length=10)),
                ('sampletube7', models.CharField(max_length=10)),
                ('sampletube8', models.CharField(max_length=10)),
                ('sampletube9', models.CharField(max_length=10)),
                ('sampletube10', models.CharField(max_length=10)),
                ('sampletube11', models.CharField(max_length=10)),
                ('sampletube12', models.CharField(max_length=10)),
                ('sampletube13', models.CharField(max_length=10)),
                ('sampletube14', models.CharField(max_length=10)),
                ('sampletube15', models.CharField(max_length=10)),
                ('sampletube16', models.CharField(max_length=10)),
                ('sampletube17', models.CharField(max_length=10)),
                ('sampletube18', models.CharField(max_length=10)),
                ('sampletube19', models.CharField(max_length=10)),
                ('sampletube20', models.CharField(max_length=10)),
                ('sampletube21', models.CharField(max_length=10)),
                ('sampletube22', models.CharField(max_length=10)),
                ('sampletube23', models.CharField(max_length=10)),
                ('sampletube24', models.CharField(max_length=10)),
                ('elutiontube1', models.CharField(max_length=10)),
                ('elutiontube2', models.CharField(max_length=10)),
                ('elutiontube3', models.CharField(max_length=10)),
                ('elutiontube4', models.CharField(max_length=10)),
                ('elutiontube5', models.CharField(max_length=10)),
                ('elutiontube6', models.CharField(max_length=10)),
                ('elutiontube7', models.CharField(max_length=10)),
                ('elutiontube8', models.CharField(max_length=10)),
                ('elutiontube9', models.CharField(max_length=10)),
                ('elutiontube10', models.CharField(max_length=10)),
                ('elutiontube11', models.CharField(max_length=10)),
                ('elutiontube12', models.CharField(max_length=10)),
                ('elutiontube13', models.CharField(max_length=10)),
                ('elutiontube14', models.CharField(max_length=10)),
                ('elutiontube15', models.CharField(max_length=10)),
                ('elutiontube16', models.CharField(max_length=10)),
                ('elutiontube17', models.CharField(max_length=10)),
                ('elutiontube18', models.CharField(max_length=10)),
                ('elutiontube19', models.CharField(max_length=10)),
                ('elutiontube20', models.CharField(max_length=10)),
                ('elutiontube21', models.CharField(max_length=10)),
                ('elutiontube22', models.CharField(max_length=10)),
                ('elutiontube23', models.CharField(max_length=10)),
                ('elutiontube24', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
