# Generated by Django 5.0.1 on 2024-02-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractionmethods', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qiasymphony24Load',
        ),
    ]
