# Generated by Django 5.0.1 on 2024-08-08 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('worksheet_number', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='invalid worksheet entered', regex='^\\d{6}$|""')])),
            ],
        ),
    ]
