# Generated by Django 5.0.1 on 2024-11-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.CharField(blank=True, max_length=150)),
                ('barcode_range_start', models.IntegerField(default=2)),
                ('barcode_range_stop', models.IntegerField(default=2)),
                ('barcode_range_step', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Check',
                'verbose_name_plural': 'Checks',
            },
        ),
    ]
