# Generated by Django 5.0.1 on 2024-11-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_check', '0002_checktable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checktable',
            options={},
        ),
    ]
