# Generated by Django 5.0.1 on 2024-11-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_check', '0003_alter_checktable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checktable',
            options={'verbose_name': 'Check Table'},
        ),
    ]
