# Generated by Django 5.0.1 on 2024-11-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_check', '0004_alter_checktable_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktable',
            name='check_hub',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='checktable',
            name='check_process',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
