# Generated by Django 5.0.1 on 2024-12-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_check', '0005_checktable_check_hub_checktable_check_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktable',
            name='check_type',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
