# Generated by Django 5.0.1 on 2025-11-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_check', '0006_checktable_check_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='extraction_worksheet',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
