# Generated by Django 5.0.1 on 2024-04-23 12:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime_check', models.DateTimeField(auto_now_add=True, verbose_name='date_and_time')),
                ('worksheet', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='invalid worksheet entered', regex='^\\d{6}$|""')])),
                ('barcode_count', models.IntegerField()),
                ('check_pass', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Check',
                'verbose_name_plural': 'Checks',
            },
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='invalid lab number entered', regex='^[A-Z]\\d{2}[.]\\d{5,6}$')])),
                ('comparisonId', models.IntegerField(null=True)),
                ('Check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match_all_check.check')),
            ],
            options={
                'verbose_name': 'Barcode',
                'verbose_name_plural': 'Barcodes',
            },
        ),
    ]
