# Generated by Django 5.0.1 on 2024-05-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_all_check', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='barcode_count',
        ),
    ]
