# Generated by Django 5.0.1 on 2024-08-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_all_check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchallcheck',
            name='check_description',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='matchpaircheck',
            name='check_description',
            field=models.CharField(blank=True),
        ),
    ]
