# Generated by Django 5.0.1 on 2024-05-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_all_check', '0002_remove_check_barcode_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='comparisonId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
