# Generated by Django 5.0.1 on 2024-08-08 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_check', '0001_initial'),
        ('match_all_check', '0002_matchallcheck_check_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchpaircheck',
            name='worksheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_check.worksheet'),
        ),
        migrations.AlterField(
            model_name='matchallcheck',
            name='worksheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_check.worksheet'),
        ),
        migrations.DeleteModel(
            name='Worksheet',
        ),
    ]
