# Generated by Django 5.0.1 on 2024-03-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_all_check', '0003_rename_check_result_check_check_pass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Barcodes',
            new_name='Barcode',
        ),
    ]
