# Generated by Django 5.0.1 on 2024-03-28 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_all_check', '0004_rename_barcodes_barcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barcode',
            options={'verbose_name': 'Barcode', 'verbose_name_plural': 'Barcodes'},
        ),
        migrations.AlterModelOptions(
            name='check',
            options={'verbose_name': 'Check', 'verbose_name_plural': 'Checks'},
        ),
        migrations.AlterField(
            model_name='barcode',
            name='barcode',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='invalid lab number entered', regex='^[A-Z]\\d{2}[.]\\d{5,6}$')]),
        ),
        migrations.AlterField(
            model_name='check',
            name='worksheet',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='invalid worksheet entered', regex='^\\d{6}$')]),
        ),
    ]
