# Generated by Django 5.0.1 on 2024-08-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_all_check', '0004_alter_matchallcheck_worksheet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchpaircheck',
            name='user',
        ),
        migrations.RemoveField(
            model_name='matchpaircheck',
            name='worksheet',
        ),
        migrations.AlterModelOptions(
            name='matchallbarcode',
            options={'verbose_name': 'matchpairbarcode'},
        ),
        migrations.AlterModelOptions(
            name='matchallcheck',
            options={'verbose_name': 'Match All Check', 'verbose_name_plural': 'Match All Checks'},
        ),
        migrations.DeleteModel(
            name='MatchPairBarcode',
        ),
        migrations.DeleteModel(
            name='MatchPairCheck',
        ),
    ]
