# Generated by Django 5.0.1 on 2024-12-04 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_all_check', '0005_remove_matchpaircheck_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchallbarcode',
            name='Check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode', to='match_all_check.matchallcheck'),
        ),
    ]
