# Generated by Django 5.0.1 on 2024-12-04 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_all_check', '0006_alter_matchallbarcode_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchallbarcode',
            name='Check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='match_all_check.matchallcheck'),
        ),
    ]
