# Generated by Django 5.0.1 on 2024-12-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_all_check', '0007_alter_matchallbarcode_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchallbarcode',
            options={'verbose_name': 'match all barcode'},
        ),
    ]
