# Generated by Django 5.0.1 on 2025-09-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_all_check', '0008_alter_matchallbarcode_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchallcheck',
            name='check_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
