# Generated by Django 4.2.7 on 2024-02-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcodecheckfunction', models.CharField(max_length=30)),
                ('dateTime_check', models.DateTimeField(auto_now_add=True, verbose_name='date_and_time')),
                ('worksheet', models.CharField(max_length=8)),
                ('barcode1', models.CharField(max_length=10)),
                ('barcode2', models.CharField(max_length=10)),
            ],
        ),
    ]
