# Generated by Django 5.0.1 on 2024-02-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodecheck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcodes',
            name='barcodeId',
        ),
        migrations.AddField(
            model_name='barcodes',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
