# Generated by Django 4.2.7 on 2024-02-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcodecheck', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BarcodeChecker',
            new_name='BarcodeCheck',
        ),
    ]
