# Generated by Django 4.2.7 on 2024-02-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcodecheck', '0002_rename_barcodechecker_barcodecheck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcodecheck',
            old_name='barcodecheckfunction',
            new_name='barcode_check_function',
        ),
    ]
