# Generated by Django 4.2.7 on 2024-02-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodecheck', '0003_rename_barcodecheckfunction_barcodecheck_barcode_check_function'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcodecheck',
            name='id',
        ),
        migrations.AddField(
            model_name='barcodecheck',
            name='barcodecheckid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
