# Generated by Django 4.2.7 on 2024-02-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodecheck', '0004_remove_barcodecheck_id_barcodecheck_barcodecheckid'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodecheck',
            name='barcodecheck_comparison_match',
            field=models.BooleanField(default=False),
        ),
    ]
