# Generated by Django 5.0.1 on 2024-02-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodecheck', '0008_alter_barcodecheck_worksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodecheck',
            name='barcode3',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barcodecheck',
            name='barcode4',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barcodecheck',
            name='barcode5',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barcodecheck',
            name='barcode6',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barcodecheck',
            name='barcode7',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barcodecheck',
            name='barcode8',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
