# Generated by Django 4.2.7 on 2024-02-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcodecheck', '0009_barcodecheck_barcode3_barcodecheck_barcode4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcodecheck',
            old_name='barcode_check_function',
            new_name='barcode_check_method',
        ),
    ]
