# Generated by Django 5.0.1 on 2024-02-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodecheck', '0010_rename_barcode_check_function_barcodecheck_barcode_check_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcodes',
            fields=[
                ('barcodeId', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=10)),
                ('comparisonId', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='BarcodeCheck',
        ),
    ]
