# Generated by Django 5.0.1 on 2024-02-26 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodecheck', '0010_rename_barcode_check_function_barcodecheck_barcode_check_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('barcode_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_barcodes', models.IntegerField()),
                ('barcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BarcodeCheck_dev',
            fields=[
                ('barcodecheckid', models.AutoField(primary_key=True, serialize=False)),
                ('barcode_check_method', models.CharField(max_length=30)),
                ('dateTime_check', models.DateTimeField(auto_now_add=True, verbose_name='date_and_time')),
                ('worksheet', models.CharField(max_length=12)),
                ('barcodecheck_result', models.BooleanField(default=False)),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='barcodecheck.barcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
