# Generated by Django 5.0.1 on 2024-08-15 08:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_check', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPairCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime_check', models.DateTimeField(auto_now_add=True, verbose_name='date_and_time')),
                ('check_number', models.IntegerField(default=1, null=True)),
                ('check_description', models.CharField(blank=True, max_length=255)),
                ('check_pass', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worksheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_check.worksheet')),
            ],
            options={
                'verbose_name': 'Match Pair Check',
                'verbose_name_plural': 'Match Pair Checks',
            },
        ),
        migrations.CreateModel(
            name='MatchPairBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='invalid lab number entered', regex='^[A-Z]\\d{2}[.]\\d{5,6}$')])),
                ('comparisonId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='match_pair_check.matchpairbarcode')),
                ('Check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match_pair_check.matchpaircheck')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
