# Generated by Django 5.0.1 on 2024-12-04 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_pair_check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchpairbarcode',
            name='Check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='match_pair_check.matchpaircheck'),
        ),
    ]
