# Generated by Django 5.0.1 on 2025-09-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_pair_check', '0002_alter_matchpairbarcode_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchpaircheck',
            name='check_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
