# Generated by Django 5.0.1 on 2024-02-28 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CultureCheck',
            fields=[
                ('culturecheck_id', models.AutoField(primary_key=True, serialize=False)),
                ('culturecheck_method', models.CharField(max_length=30)),
                ('dateTime_check', models.DateTimeField(auto_now_add=True, verbose_name='date_and_time')),
                ('culturecheckbarcode1', models.CharField(max_length=22)),
                ('culturecheckbarcode2', models.CharField(max_length=22)),
                ('culturecheckbarcode3', models.CharField(max_length=22)),
                ('culturecheckbarcode4', models.CharField(max_length=22)),
                ('culturecheckbarcode5', models.CharField(max_length=22)),
                ('culturecheckbarcode6', models.CharField(max_length=22)),
                ('culturecheckbarcode7', models.CharField(max_length=22)),
                ('culturecheckbarcode8', models.CharField(max_length=22)),
                ('culturecheckbarcode9', models.CharField(max_length=22)),
                ('culturecheckbarcode10', models.CharField(max_length=22)),
                ('culturecheckbarcode11', models.CharField(max_length=22)),
                ('culturecheckbarcode12', models.CharField(max_length=22)),
                ('culturecheckbarcode13', models.CharField(max_length=22)),
                ('culturecheckbarcode14', models.CharField(max_length=22)),
                ('culturecheckbarcode15', models.CharField(max_length=22)),
                ('culturecheckbarcode16', models.CharField(max_length=22)),
                ('culturecheck_result', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
