# Generated by Django 4.2.7 on 2024-02-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturemethods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturecheck',
            name='culturecheckbarcode1',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='culturecheck',
            name='culturecheckbarcode10',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='culturecheck',
            name='culturecheckbarcode11',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='culturecheck',
            name='culturecheckbarcode12',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='culturecheck',
            name='culturecheckbarcode13',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='culturecheck',
            name='culturecheckbarcode14',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='culturecheck',
            name='culturecheckbarcode15',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='culturecheck',
            name='culturecheckbarcode16',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='culturecheck',
            name='culturecheckbarcode2',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='culturecheck',
            name='culturecheckbarcode3',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='culturecheck',
            name='culturecheckbarcode4',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='culturecheck',
            name='culturecheckbarcode5',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='culturecheck',
            name='culturecheckbarcode6',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='culturecheck',
            name='culturecheckbarcode7',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='culturecheck',
            name='culturecheckbarcode8',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='culturecheck',
            name='culturecheckbarcode9',
            field=models.CharField(max_length=22),
        ),
    ]
